# Setup
title:        WaveDromTikZ
tagline:      An implementation of WaveDrom which outputs TikZ for use in LaTeX documents.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       mossblaser
  url:        https://github.com/mossblaser/WaveDromTikZ

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
